checks:
    javascript: true
    php: true
build:
    tests:
        override:
            -
                command: 'eslint-run ./ -c ./eslint/eslintrc.json > eslint-data' 
                analysis:
                    file: 'eslint-data'                 # The output filename
                    format: 'eslint-checkstyle'     # The supported format by Scrutinizer

            -
                command:   'shellcheck-run > shellcheck-data' 
                analysis:
                    file:   'shellcheck-data' 
                    format: 'general-checkstyle'

            -
                command: 'phpcs-run ./ --standard=./phpcs/ruleset.xml > phpcs-data'
                analysis:
                    file: 'phpcs-data'            # The reporter filename
                    format: 'php-cs-checkstyle'
