checks:
    javascript: true
    php: true
build:
    environment:
        node: v6.2.0

    tests:
        override:
            -
                command: 'eslint-run ./ -c ./eslint/eslintrc.json > eslint-data' 
                analysis:
                    file: 'eslint-data'                
                    format: 'eslint-checkstyle'    

            -
                command: 'eslint-run ./ -c ./eslint/eslintrc.json' 
                analysis:                
                    format: 'eslint-checkstyle'

            -
                command:   'shellcheck-run > shellcheck-data' 
                analysis:
                    file:   'shellcheck-data' 
                    format: 'general-checkstyle'

            -
                command: 'phpcs-run ./' 
                analysis:                
                    format: 'eslint-checkstyle'

            -
                command: 'phpcs-run ./ --standard=./phpcs/ruleset.xml > phpcs-data'
                analysis:
                    file: 'phpcs-data'           
                    format: 'php-cs-checkstyle'